# Generated by Django 5.0.1 on 2024-02-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0003_alter_book_options_alter_book_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('views__lt', 18)), name='views_menor_18'),
        ),
    ]
