# Generated by Django 5.0.1 on 2024-02-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_views_menor_18'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
