# Generated by Django 5.0.1 on 2024-02-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_loan_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
    ]
